#!/bin/bash
# MariaDB sandbox start script, generated by the mariadbSandbox shell plugin.
# The server binary path and the option file are captured here at deployment
# time so the sandbox can be started even when the binary is not on PATH.
MARIADBD=/Users/maglietti/.local/share/mariadb-sandbox-server/11.8.9/bin/mariadbd
DEFAULTS_FILE=/Users/maglietti/Code/magliettiGit/notes-app-demo/working/sandbox/3310/my.cnf
PID_FILE=/Users/maglietti/Code/magliettiGit/notes-app-demo/working/sandbox/3310/3310.pid

echo 'Starting MariaDB sandbox...'
export MYSQLD_RESTART_EXIT=16
# Run the server (and its restart loop) detached in the background so the
# terminal returns immediately. Output is redirected and the job is disowned so
# it keeps running after this script (and the shell) exits; the server logs to
# the error log configured in the option file. The script writes the PID file
# itself (so stop works regardless of how the server manages its own pid-file)
# and refreshes it across restarts (the server exits with status 16 to request
# a restart, e.g. the RESTART statement).
(
  while true ; do
    "$MARIADBD" --defaults-file="$DEFAULTS_FILE" "$@" &
    server_pid=$!
    echo "$server_pid" > "$PID_FILE"
    wait "$server_pid"
    [ $? -ne "$MYSQLD_RESTART_EXIT" ] && break
  done
  # Only clean up the PID file while it still refers to *our* server. A
  # stop-then-start cycle races here: this loop is torn down asynchronously after
  # the server exits, so a new start script can already have written its own PID
  # before we get here. Removing that would strand the new instance - stop() and
  # kill() find no PID file and refuse to act ("Could not find the PID file ...
  # although a server is listening on it"). The window is wide enough to hit in
  # practice: the port is free (so the caller proceeds) before the server process
  # is fully reaped.
  if [ "$(cat "$PID_FILE" 2>/dev/null)" = "$server_pid" ] ; then
    rm -f "$PID_FILE"
  fi
) </dev/null >/dev/null 2>&1 &
disown
echo "MariaDB sandbox started in the background."
