#!/bin/bash
# MariaDB sandbox stop script, generated by the mariadbSandbox shell plugin.
PID_FILE=/Users/maglietti/Code/magliettiGit/notes-app-demo/working/sandbox/3310/3310.pid
echo 'Stopping MariaDB sandbox...'
if [ -f "$PID_FILE" ]; then
  kill "$(cat "$PID_FILE")"
else
  echo "PID file $PID_FILE not found; the sandbox may not be running." >&2
  exit 1
fi
